[Desktop Entry]
Name=DefaultMate
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Menta
MetacityTheme=Menta
IconTheme=menta
GtkColorScheme=bg_color:#d4d4d4,selected_bg_color:#accd8a,base_color:#f7f7f7,fg_color:#2c2c2c,selected_fg_color:#f5f5f5,text_color:#2c2c2c,tooltip_bg_color:#F5F5B5,tooltip_fg_color:#000000,link_color:#61bf00,bg_color_dark:#3f3f3f,text_color_dark:#FFF
CursorTheme=
CursorSize=24
